// Do not edit this file; automatically generated by build.py.
"use strict";


// Copyright 2012 Google Inc.  Apache License 2.0
Blockly.Blocks.logic={};
// Copyright 2012 Google Inc.  Apache License 2.0
Blockly.Blocks.math={};
// Copyright 2012 Google Inc.  Apache License 2.0
Blockly.Blocks.text={};